{% set version = "1.4.1" %}

package:
  name: netcdf4
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf4-python/archive/v{{ version }}rel.tar.gz
  sha256: 8898fbd0257ddfc34fe4208af9452addc03d4e6975c5b4c95792406295119340

build:
  number: 0
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.19
    - cftime
    - hdf5
    # libnetcdf 4.4.* is the last one to work with Python 2.7 on Windows.
    - libnetcdf 4.4.*  # [win and py2k]
    - libnetcdf  # [not (win and py2k)]
  run:
    - python
    - setuptools
    - {{ pin_compatible('numpy') }}
    - cftime
    - hdf5
    # libnetcdf 4.4.* is the last one to work with Python 2.7 on Windows.
    - libnetcdf 4.4.*  # [win and py2k]
    - libnetcdf  # [not (win and py2k)]

test:
  imports:
    - netCDF4
    - cftime
  commands:
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://github.com/Unidata/netcdf4-python
  license: OSI Approved and MIT
  license_file: COPYING
  summary: 'Provides an object-oriented python interface to the netCDF version 4 library.'
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
