{% set version = "1.2.9" %}

package:
  name: netcdf4
  version: {{ version }}

source:
  fn: netCDF4-{{ version }}.tar.gz
  url: https://github.com/Unidata/netcdf4-python/archive/v{{ version }}rel.tar.gz
  sha256: bbb6d40d33f5fe8fbf211b5706ff4af9484a91a5ab50d9f6607858bd34c1d10c

build:
  number: 0
  entry_points:
    - ncinfo = netCDF4.utils:ncinfo
    - nc4tonc3 = netCDF4.utils:nc4tonc3
    - nc3tonc4 = netCDF4.utils:nc3tonc4

requirements:
  build:
    - python
    - setuptools
    - numpy 1.8.*  # [not (win and py36)]
    - numpy 1.11.*  # [win and py36]
    - cython >=0.19
    - hdf5 1.8.18|1.8.18.*
    - libnetcdf 4.4.*
  run:
    - python
    - setuptools
    - numpy >=1.8  # [not (win and py36)]
    - numpy >=1.11  # [win and py36]
    - hdf5 1.8.18|1.8.18.*
    - libnetcdf 4.4.*

test:
  imports:
    - netCDF4
    - netcdftime
  commands:
    - ncinfo -h
    - nc4tonc3 -h
    - nc3tonc4 -h
    - conda inspect linkages -p $PREFIX netcdf4  # [not win]
    - conda inspect objects -p $PREFIX netcdf4  # [osx]

about:
  home: http://github.com/Unidata/netcdf4-python
  license: OSI Approved and MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING'
  summary: 'Provides an object-oriented python interface to the netCDF version 4 library.'
  dev_url: https://github.com/Unidata/netcdf4-python
  doc_url: https://unidata.github.io/netcdf4-python

extra:
  recipe-maintainers:
    - ocefpaf
    - pelson
    - dopplershift
